### ISSUE TITLE
Publish to Maven repo

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/springboot-support#9]
It is necessary to publish the library in the Maven repository of Cloudstate, preferably via travis

**Comment by sleipnir** [comment]
I send commit for provide this https://github.com/cloudstateio/springboot-support/commit/59da86c9a28c39e2d808e1bee6af3ec2d3df9f30

**Comment by sleipnir** [comment]
Some work still needs to be done for everything to work

**Comment by pvlugter** [comment]
I'll take a look at this, publishing via bintray, with sync to maven central.

**Comment by sleipnir** [comment]
Awesome @pvlugter thanks!
